Repository arcalot/arcaflow-engine, pull requests merged in 2023-10, with the labels that each got.

#113 update readme
  README.md
Labels: documentation

#116 Fix and Update CI Regular Expression
  .github/workflows/build.yml
Labels: bug

#114 ATP v3, Validate Compatibility, Improved stop_if, better logs, retry fix
  cmd/arcaflow/main.go
  cmd/run-plugin/run.go
  engine_test.go
  go.mod
  go.sum
  internal/step/dummy/provider.go
  internal/step/dummy/provider_test.go
  internal/step/foreach/provider.go
  internal/step/plugin/provider.go
  internal/step/plugin/provider_test.go
  internal/step/provider.go
  workflow/any.go
  workflow/executor.go
  workflow/executor_test.go
  workflow/model.go
  workflow/workflow.go
  workflow/workflow_test.go
Labels: bug, enhancement
